target_app_name = "Path of Exile"
active_profile_name = "anim_weapon"
widget_buttons_position = [ 515, 486,]

[paths]
path_frame_buttons_ui = "res\\frame_buttons.ui"
path_frame_recorder_ui = "res\\frame_recorder.ui"
path_icon_running = "res\\running.png"
path_icon_stopped = "res\\stopped.png"
path_profiles = "profiles"

[checkboxes]
S = true
H = true
Hv = true
M = true
Mv = true
