target_app_name = "Path of Exile"
active_profile_name = "3_28_expl_arrow"
widget_buttons_position = [ 691, 1047,]

[paths]
path_frame_buttons_ui = "res\\frame_buttons.ui"
path_frame_recorder_ui = "res\\frame_recorder.ui"
path_icon_running = "res\\running.png"
path_icon_stopped = "res\\stopped.png"
path_profiles = "profiles"

[checkboxes]
S = false
H = false
Hv = false
M = false
Mv = false
