active = false

[autoheal]
active = true
low_lim = 13
high_lim = 60
timeout = 1000
keys = [ [ 1, 2, 3,], [ 4, 5,],]

[automana]
active = true
low_lim = 13
high_lim = 60
timeout = 1000
keys = [ [ 1, 2, 3,], [ 4, 5,],]

[paths]
target_app_name = "Path of Exile"
path_frame_buttons_ui = "c:\\_software\\poe_overlay\\poe_overlay\\res\\frame_buttons.ui"
path_frame_recorder_ui = "c:\\_software\\poe_overlay\\poe_overlay\\res\\frame_recorder.ui"
path_icon_running = "c:\\_software\\poe_overlay\\poe_overlay\\res\\running.png"
path_icon_stopped = "c:\\_software\\poe_overlay\\poe_overlay\\res\\stopped.png"

[frame_buttons]
geometry = [ 600, 1000, 0, 0,]
css = "QFrame{background-color: rgb(100, 100, 100);} QWidget{background-color: green;} QPushButton{background-color: green;font: 10pt 'MS Shell Dlg 2';}"
button_active = "background-color: lightgreen"
button_inactive = "background-color: green"

[frame_health_bar]
geometry = [ 105, 910, 15, 180,]
css = "QLabel {background-color: transparent;border: 1px solid red;color: white;font-size: 14px;}"

[frame_health_value]
geometry = [ 240, 910, 70, 70,]
css = "QLabel {background-color: rgba(14, 255, 255, 210);color: white;font: 18 24pt 'MS Shell Dlg 2';}"

[frame_mana_bar]
geometry = [ 1600, 910, 15, 180,]
css = "QLabel {background-color: transparent;border: 1px solid blue;color: white;font-size: 14px;}"

[frame_mana_value]
geometry = [ 1500, 910, 70, 70,]
css = "QLabel {background-color: rgba(14, 255, 255, 210);color: white;font: 18 24pt 'MS Shell Dlg 2';}"

[frame_scan]
geometry = [ 5, 29, 1910, 1120,]
css = "QLabel {background-color: transparent;border: 2px solid red;color: white;font-size: 14px;}"

[frame_stop_watch]
geometry = [ 340, 950, 80, 30,]
css = "QLabel {background-color: rgba(14, 255, 255, 210);color: white;font: 18 24pt 'MS Shell Dlg 2';}"

[remap_mouse.wheel_forward]
active = true
timeout = 2
flasks = [ [ 3, 4, 5,],]
hotkey = "wheel_forward"

[remap_mouse.wheel_backward]
active = false
timeout = 2
hotkey = "wheel_backward"

[remap_mouse.use_skill_repeatedly]
active = false
timeout = 1
toggle = true
hotkey = "use_skill_repeatedly"

[remap_keyboard.fast_click_left_with_ctrl_down]
active = true
hotkey = "f4"

[remap_keyboard.fast_click_left_with_shift_down]
active = true
hotkey = "f5"

[remap_keyboard.use_portal_scroll]
active = true
hotkey = "`"

[remap_keyboard.use_skill_repeatedly]
active = true
hotkey = "space"
timeout = 10
